name: Deploy to demo

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]
    branches:
      - main

jobs:
  build-and-deploy-demo:
    name: Call reusable workflow when pull request is created
    if: github.event.pull_request.draft == false
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-deploy.yaml@main
    with:
      app_name: new-dataset-catalog-gui
      caller_sha: ${{ github.sha }}
      repo: ${{ github.repository }}
      actor: ${{ github.actor }}
      environment: demo
      cluster: digdir-fdk-dev
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GCP_SA_DIGDIR_FDK_GCR_KEY: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  build-dev-image:
    name: Build and test dev image on PR from dependabot
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    uses: Informasjonsforvaltning/workflows/.github/workflows/build.yaml@main
    with:
      caller_sha: ${{ github.sha }}
      repo: ${{ github.repository }}
      actor: ${{ github.actor }}
      dockerfile: dev.Dockerfile
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}